#!/usr/bin/env python
'''
Directly call a salt command in the modules, does not require a running salt
minion to run.
'''

from salt.scripts import salt_stream_client


if __name__ == '__main__':
    salt_stream_client()
